// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWtzjeMxW_Fan0HkSwZ5uaIDlS8yU9hPw',
    appId: '1:264114923673:web:1f4b2de7f33a1ada36b008',
    messagingSenderId: '264114923673',
    projectId: 'threads-45e7a',
    authDomain: 'threads-45e7a.firebaseapp.com',
    storageBucket: 'threads-45e7a.appspot.com',
    measurementId: 'G-0DWK0X2S2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpe-wxVSyHRycWzNEWyRe3ERGUdE0rnDs',
    appId: '1:264114923673:android:578a0f3d20c0147336b008',
    messagingSenderId: '264114923673',
    projectId: 'threads-45e7a',
    storageBucket: 'threads-45e7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSHhC6K5WL7T6K3zrKLq5AiYLCZBvMbzc',
    appId: '1:264114923673:ios:d260c84162d3a65036b008',
    messagingSenderId: '264114923673',
    projectId: 'threads-45e7a',
    storageBucket: 'threads-45e7a.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSHhC6K5WL7T6K3zrKLq5AiYLCZBvMbzc',
    appId: '1:264114923673:ios:3b34556ac69ec47a36b008',
    messagingSenderId: '264114923673',
    projectId: 'threads-45e7a',
    storageBucket: 'threads-45e7a.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
